services:

  arangodb_single_server:
    container_name: arangodb-single-server-instance
    image: arangodb/arangodb
    ports:
      - 10000:8529
    environment:
      - ARANGO_ROOT_PASSWORD=""
      - ARANGO_NO_AUTH=false
    volumes:
      - ./adb_single_server/data:/var/lib/arangodb3
      - ./adb_single_server/apps:/var/lib/arangodb3-apps
      - ./secrets.jwt/token:/secrets/token:ro
    command: arangodb --starter.mode=single --auth.jwt-secret=./secrets/token

  arangodb_cluster:
    container_name: arangodb-cluster-instance
    image: arangodb/arangodb
    ports:
      - 8529:8529
    volumes:
      - ./secrets.jwt/token:/secrets/token:ro
    environment:
      - ARANGO_ROOT_PASSWORD=""
      - ARANGO_NO_AUTH=false
    command: arangodb --mode=cluster --local=true --auth.jwt-secret=./secrets/token

  neo4j:
    container_name: neo4j-instance
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/superadmin
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/plugins:/plugins
